* -----------------------------------------------------
* XLS2GMS 2.8      24.1.3 r41464 Released Jul 26, 2013 VS8 x86/MS Windows       
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    D:\Sync\Dropbox\dldo\proj\input_UC_ii.xlsx
* Sheet:       wind_test(Sheet5)
* Range:       $AD$4:$AE$14
* -----------------------------------------------------
       column1             
scen1  0.02                
scen2  0.160000000000001   
scen3  0.107272727272728   
scen4  0.241818181818183   
scen5  0.107272727272728   
scen6  0.150000000000001   
scen7  0.0863636363636365  
scen8  0.000909090909090909
scen9  0.125454545454546   
scen10 0.000909090909090909
* -----------------------------------------------------
